### PR TITLE
Prepare for renaming default branch

### PR DESCRIPTION
**Pull request by johnsyweb**
#### Context

As alluded to in #80, it's more inclusive to name the [Git default branch as `main`](https://www.hanselman.com/blog/easily-rename-your-git-default-branch-from-master-to-main)/), so let's do that.

#### Change

Use HEAD commit on default branch for URIs

#### Considerations

There's probably enough in the Changelog to warrant a v0.5.0 release now.

### CODE REVIEW

**Review by joesustaric — APPROVED** [review]
gah I had this as a comment I forgot to post on the other PR.. 
Thanks for making the change

**Comment by joesustaric** [comment]
I'm still approving even though my ticks are grey 😿 .

**Review by Domon — APPROVED** [review]

**Review by orien — APPROVED** [review]
🎉

**Comment by johnsyweb** [comment]
Default branch has been named `main`.

**Pull request merged**
